#### SciKit Learn Preprocessing

In [2]:
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = np.random.randint(0, 100, (10, 2))

In [12]:
data

array([[91, 17],
       [37, 96],
       [75, 34],
       [39, 78],
       [24, 20],
       [24, 62],
       [25, 62],
       [68, 21],
       [96, 76],
       [14, 87]])

#### Scaling the data

In [7]:
scaler_model = MinMaxScaler()

In [8]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [9]:
# fit the data allow the model to learn
scaler_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [10]:
# normalize data
# divide each value in each column by max value of that column
scaler_model.transform(data)

array([[0.93902439, 0.        ],
       [0.2804878 , 1.        ],
       [0.74390244, 0.21518987],
       [0.30487805, 0.7721519 ],
       [0.12195122, 0.03797468],
       [0.12195122, 0.56962025],
       [0.13414634, 0.56962025],
       [0.65853659, 0.05063291],
       [1.        , 0.74683544],
       [0.        , 0.88607595]])

In [11]:
# in the other hand we can do in one step
scaler_model.fit_transform(data)


array([[0.93902439, 0.        ],
       [0.2804878 , 1.        ],
       [0.74390244, 0.21518987],
       [0.30487805, 0.7721519 ],
       [0.12195122, 0.03797468],
       [0.12195122, 0.56962025],
       [0.13414634, 0.56962025],
       [0.65853659, 0.05063291],
       [1.        , 0.74683544],
       [0.        , 0.88607595]])

#### Split test set and train set


In [13]:
import pandas as pd

In [14]:
# generate sample data

In [15]:
mydata = np.random.randint(0, 101, (50, 4))

In [16]:
mydata

array([[  0,  78,  65,  48],
       [ 72,   0,  71,  37],
       [ 62,  85,  74,  76],
       [ 30,  16,  45,  36],
       [ 48,  29,  52,  85],
       [ 59,  76,  46,  26],
       [ 54,  64,  19,  51],
       [ 17,  21,  20,  23],
       [ 44,   4,  61,   3],
       [ 98,  42,   7,  64],
       [ 28,  24,  72,  71],
       [ 18,  29,  88,   8],
       [ 36,  95,  35,  39],
       [ 85,  99,  47,  92],
       [ 20,  37,  98,  12],
       [ 97,  11,   6,   2],
       [ 93,  11,  66,  46],
       [ 76,  57,  19, 100],
       [ 73,  25,  76,  95],
       [ 77,  60,  27,  42],
       [ 51,  44,  77,   5],
       [ 24,  41,  18,  73],
       [ 46,  84,  19,  80],
       [ 76,  58,  49,  31],
       [  7,  61,  72,  66],
       [ 73,  95,  17,   0],
       [ 21,   8,  91,  70],
       [ 27,  80,  14,   6],
       [ 37,   8,  19,  95],
       [  1,  75,  31,  43],
       [ 32,  19,  32,  33],
       [ 54,  63,   0,  98],
       [ 54,  74,  87,  99],
       [ 94,   4,  68,  67],
       [ 50,  

In [21]:
df = pd.DataFrame(data=mydata, columns=['f1', 'f2', 'f3','label'])

In [22]:
df

f1  f2   f3  label
0    0  78   65     48
1   72   0   71     37
2   62  85   74     76
3   30  16   45     36
4   48  29   52     85
5   59  76   46     26
6   54  64   19     51
7   17  21   20     23
8   44   4   61      3
9   98  42    7     64
10  28  24   72     71
11  18  29   88      8
12  36  95   35     39
13  85  99   47     92
14  20  37   98     12
15  97  11    6      2
16  93  11   66     46
17  76  57   19    100
18  73  25   76     95
19  77  60   27     42
20  51  44   77      5
21  24  41   18     73
22  46  84   19     80
23  76  58   49     31
24   7  61   72     66
25  73  95   17      0
26  21   8   91     70
27  27  80   14      6
28  37   8   19     95
29   1  75   31     43
30  32  19   32     33
31  54  63    0     98
32  54  74   87     99
33  94   4   68     67
34  50  12   81     99
35  52  50   93    100
36  58  36   79     94
37   2  77   18     72
38  16   8    0     21
39  24  38  100     28
40  50  86   16     51
41  86  27   91     56
42  31   5   50      7
43  46  88   86     22
44  80  94   70      6
45   7  38   72     84
46   6  68   51     45
47  55  85   74     17
48  54  63   92     85
49  24  36   66     96

In [23]:
# feature and label
X = df[['f1', 'f2', 'f3']]

In [26]:
y = df['label']

In [25]:
# split data
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [30]:
X_train.shape

(35, 3)

In [31]:
X_test.shape

(15, 3)