### TF Basic Syntax

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


## Tensors

In [7]:
hello = tf.constant("Hello")


In [8]:
word = tf.constant('word')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    result = sess.run(hello + word)


In [11]:
print(result)

b'Helloword'


** Computation **

In [12]:
a = tf.constant(10)

In [13]:
b = tf.constant(20)

In [14]:
type(a)

tensorflow.python.framework.ops.Tensor

In [15]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [16]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [17]:
print(result)

30


## Operations

In [19]:
const = tf.constant(10)

In [20]:
fill_mat = tf.fill((4,4), 10)

In [23]:
myzeros = tf.zeros((4,4))

In [25]:
myones = tf.ones((4,4))

In [26]:
myrand = tf.random_normal((4,4), mean=0, stddev=1.0)

In [28]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [29]:
my_ops = [const, fill_mat, myzeros, myones, myrand, myrandu]

## Interactive Session

Useful for Notebook Sessions

In [30]:
sess = tf.InteractiveSession()

In [32]:
for op in my_ops:
    print(sess.run(op))
    print()

10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[ 0.0144396  -1.0097932  -0.6025182   0.6672852 ]
 [ 2.131026    0.29121804  0.2655761  -0.01667947]
 [ 0.09835228  0.68724567 -0.7308513  -0.10264385]
 [-1.6834394  -0.17166273  0.4585261   2.6210425 ]]

[[0.24852312 0.19849241 0.70635533 0.36893094]
 [0.35054076 0.30469525 0.37535822 0.57600117]
 [0.56262434 0.23185253 0.03756797 0.07034171]
 [0.33060443 0.7125448  0.15372753 0.74029946]]



In [34]:
for op in my_ops:
    print(op.eval())
    print()

10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[ 0.09557083  0.02398961  0.5282006   0.11312246]
 [ 1.5650148   0.48050454 -1.1131768  -0.7534249 ]
 [-0.04092094 -0.25108114  0.58904964  1.8930944 ]
 [ 0.8974073  -0.30317387  0.5186326  -0.9640422 ]]

[[0.8067609  0.17608023 0.47316313 0.2765    ]
 [0.840418   0.7361971  0.5108905  0.7954892 ]
 [0.40186203 0.19449985 0.81269526 0.78055906]
 [0.76757884 0.8916588  0.92653644 0.96968305]]



## Matrix Multiplication

In [35]:
a = tf.constant([[1,2],[3,4]])

In [36]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [37]:
b = tf.constant([[10], [100]])

In [38]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [39]:
result = tf.matmul(a, b)

In [40]:
result.eval()

array([[210],
       [430]], dtype=int32)